# -*- coding: utf-8 -*-
"""YOLOv5Tumors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xRZbYySIFvyzD5QhrDwq-Of5celQq7KJ
"""

!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

!cd yolov5

!pip install -r /content/drive/MyDrive/requirements.txt

import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

model

!cd /content/drive/MyDrive/labelImg && pyrcc5 -o libs/resources.py resources.qrc

!pip install pyqt5 lxml --upgrade

!cd /content/drive/MyDrive/yolov5 && python train.py --img 320 --batch 16 --epochs 500 --data dataset.yml --weights yolov5s.pt --workers 2

model = torch.hub.load('ultralytics/yolov5', 'custom', path='/content/drive/MyDrive/yolov5/runs/train/exp12/weights/last.pt', force_reload=True)

import os
img = os.path.join('data', 'images', '/content/drive/MyDrive/Benign-Tumor-left-and-Malignant-Tumor-Right-5.jpg')

results = model(img)
results.print()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()

import os
img = os.path.join('data', 'images', '/content/drive/MyDrive/Data/y424.jpg')

results = model(img)
results.print()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()

# Commented out IPython magic to ensure Python compatibility.
import os
img = os.path.join('data', 'images', '/content/drive/MyDrive/Data/y180.jpg')
results = model(img)
results.print()
# %matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()

# Commented out IPython magic to ensure Python compatibility.
import os
img = os.path.join('data', 'images', '/content/drive/MyDrive/Data/Y245.jpg')
results = model(img)
results.print()
# %matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()